Real time censoring playback
PatrickDuncan/cleansio pull request #146
Opened 2019-04-04 06:12 UTC by levin-noro

For #135 

Initial version for review and testing.
Will cleanup print statements and do any refactoring in subsequent versions.

2019-04-06 19:30 UTC, PatrickDuncan requested changes

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +    def run(self):
You should break up this huge function in a few methods

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +                clean_frames, sample_rate = sf.read(clean_chunk_filepath,dtype='float32',fill_value=0.0,frames=int(44100*5),always_2d=True)
Spaces between params

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +        if status:
Remove debug prints?

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +        with self.processing_lock:
`# Comments should looks like this`

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +                print('#' * 80)
Remove debugging prints

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +from pydub import AudioSegment
Library imports, then our imports. Linting will tell you anyways

2019-04-06 19:30 UTC, PatrickDuncan commented on cleansio/censor/censor.py
> +                print('Found ' + str(stamp) + ' at index ' + str(chunk_index))
Remove debugging

2019-04-24 18:16 UTC, levin-noro commented on cleansio/censor/censor_realtime_mac.py
> +                print('#' * 80)
This print provides useful instructions

2019-04-24 18:17 UTC, levin-noro commented on cleansio/censor/censor_realtime_mac.py
> +        overlapping_chunk = chunk1[2500:] + chunk2[:2500]
For whatever reason, this results in an overlapping_chunk that is chunk1[2500:] + **chunk1**[:2500]. It makes absolutely no sense, and I can't figure out why its happening

2019-04-24 19:36 UTC, PatrickDuncan requested changes

2019-04-24 19:36 UTC, PatrickDuncan commented on cleansio/audio/convert.py
> +    chunk.set_channels(1)      \
Inconsistent styling

2019-04-24 19:36 UTC, PatrickDuncan commented on cleansio/censor/censor.py
> +        # print('lyrics = '+str(lyrics))
remove debug prints

2019-04-24 19:36 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +                print('press Return to stop censoring')
Capital p?

2019-04-24 19:36 UTC, PatrickDuncan commented on cleansio/utils/__init__.py
> +from .mac import MacUtil
needs newline

2019-04-24 19:36 UTC, PatrickDuncan commented on cleansio/utils/cleanup.py
> +    # remove_chunks()
?

2019-04-25 01:10 UTC, levin-noro commented on cleansio/censor/censor_realtime_mac.py
> +        overlapping_chunk = chunk1[2500:] + chunk2[:2500]
Resolved by using indata.copy()

2019-04-26 01:06 UTC, PatrickDuncan submitted a review, later dismissed

2019-04-26 22:17 UTC, PatrickDuncan requested changes

2019-04-26 22:17 UTC, PatrickDuncan commented on cleansio/censor/censor_realtime_mac.py
> +            with sd.Stream(device=(2, 1),
The methods for looking for the desired sound device are already in the repo. Please fix the hard code

2019-04-27 00:02 UTC, PatrickDuncan requested changes
After that I'll merge

2019-04-27 00:02 UTC, PatrickDuncan commented on tests/censor/test_censor.py
> +test_censor()
Was this for debugging?

2019-04-27 04:38 UTC, PatrickDuncan approved these changes

2019-04-27 04:42 UTC, merged